[package]
name = "os"
version = "0.1.0"
authors = ["LyricZhao <lyricz@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = {git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
spin = "*"
buddy_system_allocator = "*"
xmas-elf = "*"
rcore-fs = { git = "https://github.com/rcore-os/rcore-fs", rev = "d8d61190" }
rcore-fs-sfs = { git = "https://github.com/rcore-os/rcore-fs", rev = "d8d61190" }

[dependencies.lazy_static]
version = "*"
features = ["spin_no_std"]